/**
 * AUTO-GENERATED – do not edit by hand.
 * Source: src/constants/listings.js
 * Regenerate: npm run sync-listings (from repo root)
 */

export const categoryInfo = {
  realestate: { name: 'Үл хөдлөх', icon: '🏠', color: 'from-blue-500 to-blue-600' },
  vehicles: { name: 'Автомашин', icon: '🚗', color: 'from-red-500 to-red-600' },
  electronics: { name: 'Электроник', icon: '📱', color: 'from-purple-500 to-purple-600' },
  jobs: { name: 'Ажлын байр', icon: '💼', color: 'from-green-500 to-green-600' },
  services: { name: 'Үйлчилгээ', icon: '🔧', color: 'from-yellow-500 to-yellow-600' },
  fashion: { name: 'Хувцас/Косметик', icon: '👕', color: 'from-pink-500 to-pink-600' },
  furniture: { name: 'Тавилга', icon: '🛋️', color: 'from-amber-500 to-amber-600' },
  cargo: { name: 'Карго', icon: '📦', color: 'from-teal-500 to-teal-600' },
  community: { name: 'Утас/Дугаар', icon: '📞', color: 'from-indigo-500 to-indigo-600' },
  free: { name: 'Үнэгүй', icon: '🎁', color: 'from-emerald-500 to-emerald-600' },
  other: { name: 'Бусад', icon: '📦', color: 'from-gray-500 to-gray-600' },
};

export const subcategoryConfig = {
  realestate: [
    { value: 'sell', label: 'Зарна' },
    { value: 'rent', label: 'Түрээслүүлнэ' },
    { value: 'buy_request', label: 'Агуулах' },
    { value: 'apartment', label: 'Орон сууц' },
    { value: 'house', label: 'Байшин' },
    { value: 'office', label: 'Оффис' },
    { value: 'land', label: 'Газар' },
    { value: 'commercial', label: 'Арилжааны талбай' },
    { value: 'other', label: 'Бусад' },
  ],
  vehicles: [
    { value: 'sell', label: 'Зарна' },
    { value: 'rent', label: 'Түрээслүүлнэ' },
    { value: 'car', label: 'Автомашин' },
    { value: 'suv', label: 'Жийп' },
    { value: 'truck', label: 'Ачааны машин' },
    { value: 'motorcycle', label: 'Мотоцикл' },
    { value: 'bicycle', label: 'Дугуй' },
    { value: 'parts', label: 'Сэлбэг хэрэгсэл' },
    { value: 'other', label: 'Бусад' },
  ],
  electronics: [
    { value: 'sell', label: 'Зарна' },
    { value: 'buy_request', label: 'Агуулах' },
    { value: 'phone', label: 'Гар утас' },
    { value: 'laptop', label: 'Зөөврийн компьютер' },
    { value: 'desktop', label: 'Компьютер' },
    { value: 'tablet', label: 'Таблет' },
    { value: 'camera', label: 'Камер' },
    { value: 'tv', label: 'Телевиз' },
    { value: 'audio', label: 'Аудио' },
    { value: 'gaming', label: 'Тоглоом' },
    { value: 'accessories', label: 'Дагалдах хэрэгсэл' },
    { value: 'other', label: 'Бусад' },
  ],
  jobs: [
    { value: 'full_time', label: 'Бүтэн цагийн ажил' },
    { value: 'part_time', label: 'Цагийн ажил' },
    { value: 'freelance', label: 'Фрилансер' },
    { value: 'internship', label: 'Дадлага' },
    { value: 'looking_for_job', label: 'Ажил хайж байна' },
    { value: 'it', label: 'IT/Програм хангамж' },
    { value: 'marketing', label: 'Маркетинг' },
    { value: 'sales', label: 'Борлуулалт' },
    { value: 'service', label: 'Үйлчилгээ' },
    { value: 'construction', label: 'Барилга' },
    { value: 'education', label: 'Боловсрол' },
    { value: 'other', label: 'Бусад' },
  ],
  services: [
    { value: 'cargo', label: 'Карго/Илгээмж' },
    { value: 'translation', label: 'Орчуулга' },
    { value: 'visa', label: 'Виз зуучлал' },
    { value: 'repair', label: 'Засвар' },
    { value: 'food_delivery', label: 'Хоол хүргэлт' },
    { value: 'room_rental', label: 'Байр түрээс/зуучлал' },
    { value: 'cleaning', label: 'Цэвэрлэгээ' },
    { value: 'moving', label: 'Нүүлгэн шилжүүлэлт' },
    { value: 'beauty', label: 'Гоо сайхан' },
    { value: 'tutoring', label: 'Багшлах' },
    { value: 'photography', label: 'Зураг авалт' },
    { value: 'design', label: 'Дизайн' },
    { value: 'catering', label: 'Хоол' },
    { value: 'event', label: 'Арга хэмжээ' },
    { value: 'legal', label: 'Хууль зүй' },
    { value: 'accounting', label: 'Нягтлан бодох' },
    { value: 'other', label: 'Бусад' },
  ],
  fashion: [
    { value: 'cosmetics', label: 'Солонгосын косметик' },
    { value: 'kpop', label: 'K-pop related' },
    { value: 'mens', label: 'Эрэгтэй хувцас' },
    { value: 'womens', label: 'Эмэгтэй хувцас' },
    { value: 'kids', label: 'Хүүхдийн хувцас' },
    { value: 'shoes', label: 'Гутал' },
    { value: 'bags', label: 'Цүнх' },
    { value: 'accessories', label: 'Гоёл чимэглэл' },
    { value: 'watches', label: 'Цаг' },
    { value: 'jewelry', label: 'Үнэт эдлэл' },
    { value: 'sportswear', label: 'Спорт хувцас' },
    { value: 'other', label: 'Бусад' },
  ],
  furniture: [
    { value: 'bedroom', label: 'Унтлагын өрөө' },
    { value: 'living_room', label: 'Зочны өрөө' },
    { value: 'kitchen', label: 'Гал тогооны өрөө' },
    { value: 'office', label: 'Оффис' },
    { value: 'outdoor', label: 'Гадна' },
    { value: 'lighting', label: 'Гэрэлтүүлэг' },
    { value: 'storage', label: 'Хадгалалт' },
    { value: 'decor', label: 'Чимэглэл' },
    { value: 'other', label: 'Бусад' },
  ],
  cargo: [
    { value: 'air', label: 'Агаарын карго' },
    { value: 'ground', label: 'Газрын карго' },
    { value: 'ground_express', label: 'Газрын експресс' },
    { value: 'intercity', label: 'Хот хооронд' },
    { value: 'other', label: 'Бусад' },
  ],
  community: [
    { value: 'phone_sell', label: 'Гар утас зарна' },
    { value: 'number_sell', label: 'Дугаар зарна' },
    { value: 'sim_card', label: 'Сим карт' },
    { value: 'other', label: 'Бусад' },
  ],
  free: [
    { value: 'give', label: 'Үнэгүй өгөх' },
    { value: 'other', label: 'Бусад' },
  ],
  other: [
    { value: 'books', label: 'Ном' },
    { value: 'sports', label: 'Спорт' },
    { value: 'toys', label: 'Тоглоом' },
    { value: 'musical', label: 'Хөгжим' },
    { value: 'garden', label: 'Цэцэрлэг' },
    { value: 'tools', label: 'Багаж хэрэгсэл' },
    { value: 'collectibles', label: 'Цуглуулга' },
    { value: 'free', label: 'Үнэгүй' },
    { value: 'other', label: 'Бусад' },
  ],
};

/** Condition labels for display (e.g. badge, detail) */
export const conditionLabels = {
  new: 'Шинэ',
  like_new: 'Бараг шинэ',
  used: 'Хэрэглэсэн',
  for_parts: 'Сэлбэгт',
};

/** Condition options for forms (Select, chips) */
export const conditionOptions = [
  { value: 'new', label: 'Шинэ' },
  { value: 'like_new', label: 'Бараг шинэ' },
  { value: 'used', label: 'Хэрэглэсэн' },
  { value: 'for_parts', label: 'Сэлбэгт' },
];

export const locations = [
  'Seoul',
  'Busan',
  'Incheon',
  'Daegu',
  'Gyeonggi-do',
  'Gyeongsangnam-do',
  'Бусад',
];
